Feature/main 4.6
EvillFuryCat/TaskManager pull request #13
Opened 2022-10-16 16:51 UTC by EvillFuryCat

2022-10-18 21:24 UTC, aleksandr-semenov-dbp requested changes

2022-10-18 21:24 UTC, aleksandr-semenov-dbp commented on test/test_tags.py
> +        assert response.status_code == HTTPStatus.OK, response.content
здесь надо создать пару экземпляров тэгов, получить лист и сверить его с тем, который должен был получиться

2022-10-18 21:24 UTC, aleksandr-semenov-dbp commented on test/test_tags.py
> +        expected_response = self.retrieve(tag["id"])
expected_response - это то, что ожидается, и его надо сравнивать с тем что реально вернула тестируемая функция (то же дальше)

2022-10-18 21:24 UTC, aleksandr-semenov-dbp commented on test/test_tags.py
> +        assert response.status_code == HTTPStatus.FORBIDDEN, response.content
Хорошо бы проверить еще и содержимое ошибки

2022-10-21 07:23 UTC, aleksandr-semenov-dbp requested changes

2022-10-21 07:23 UTC, aleksandr-semenov-dbp commented on docker-compose.yml
> +      - .:/app
Этого вольюма быть не должно, что-то делается не так. Я думаю отсюда и вся эта куча мусора __pycache__ *.pyc - этого тоже быть не должно. Тут похоже что в докеровском контейнере проделана огромная дырка через которую ты смотришь на код на своей локальной машине, и вероятно что-то с нее запускаешь. Назначение докера - создать повторяемую среду, чтобы я на своей машине и сервер в облаке могли запустить код одинаково независимо от того, что на моей машине или сервере локально установлено, а такой подход ломает повторяемость, надо разобраться с этим, убрать вольюм и мусор. Запускать все в среде `docker-compose run --rm api bash`

2022-10-21 09:04 UTC, EvillFuryCat commented on docker-compose.yml
> +      - .:/app
так было удобнее вносить изменения в коде, до этого редактировал все файлы через vim прямо в контейнере. 
А постоянно билдить образ, на моем компе занимает минут 7, и я поставил эту настройку ради экономии времени.

2022-10-24 15:29 UTC, aleksandr-semenov-dbp approved these changes

2022-10-24 16:49 UTC, merged